import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const generated = resolve(root, "dist/index.html");
const homepage = resolve(root, "index.html");

const html = await readFile(generated, "utf8");
if (!html.includes("<!-- Generated by Eleventy")) {
  throw new Error("The generated homepage is missing its Eleventy marker.");
}
await writeFile(homepage, html.replace(/[ \t]+$/gm, ""), "utf8");
console.log("Updated index.html for GitHub Pages.");
